---
# Flux GitOps Konfiguration - Ready-to-Use Examples
# Platziere in: clusters/dev/ (bzw. staging/prod)

# ===== 1. Git Repository Source =====
# Datei: clusters/dev/infrastructure/sources.yaml

apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: cluster-config
  namespace: flux-system
spec:
  interval: 30s
  url: https://github.com/YOUR_USER/k8s-cluster-config
  ref:
    branch: main
  secretRef:
    name: flux-system
  ignore: |
    # Files to ignore
    *.md
    .github/
    terraform/
    docs/

---
# ===== 2. Flux Sync Configuration =====
# Datei: clusters/dev/infrastructure/flux-sync.yaml

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-config
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/dev
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: cluster-config
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: "*"
      namespace: monitoring
      timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-age

---
# ===== 3. Namespace Setup =====
# Datei: clusters/dev/apps/namespaces.yaml

apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted

---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    environment: dev

---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    prometheus: "true"
    environment: dev

---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
  labels:
    logging: "true"
    environment: dev

---
# ===== 4. Helm Repository Sources =====
# Datei: clusters/dev/infrastructure/helm-repos.yaml

apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  interval: 1h
  url: https://prometheus-community.github.io/helm-charts

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 1h
  url: https://grafana.github.io/helm-charts

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jetstack
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.jetstack.io

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 1h
  url: https://kubernetes.github.io/ingress-nginx

---
# ===== 5. ConfigMap mit Umgebungsvariablen =====
# Datei: clusters/dev/apps/config.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: default
data:
  ENVIRONMENT: "dev"
  CLUSTER_NAME: "k8s-dev"
  DOMAIN: "cluster.local"
  LOG_LEVEL: "info"
  GRAFANA_ADMIN_USER: "admin"

---
# ===== 6. Prometheus + Grafana via Helm =====
# Datei: clusters/dev/apps/monitoring.yaml

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "55.0.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 1h

  install:
    crds: Create
    remediation:
      retries: 3
  
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
  
  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              kind: Service
              name: prometheus-kube-prometheus-prometheus
            patch:
              - op: replace
                path: /spec/type
                value: LoadBalancer
              - op: add
                path: /spec/loadBalancerIP
                value: "192.168.100.200"

  values:
    prometheus:
      prometheusSpec:
        retention: 30d
        retentionSize: "10GB"
        scrapeInterval: 30s
        evaluationInterval: 30s
        
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi
        
        additionalScrapeConfigs:
          - job_name: kubernetes-pods
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                action: keep
                regex: true
              - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
                action: replace
                target_label: __metrics_path__
                regex: (.+)
              - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
                action: replace
                regex: ([^:]+)(?::\d+)?;(\d+)
                replacement: $1:$2
                target_label: __address__

    grafana:
      enabled: true
      adminPassword: "${GRAFANA_PASSWORD}"  # From secret
      adminUser: admin
      
      persistence:
        enabled: true
        size: 5Gi
      
      datasources:
        datasources.yaml:
          apiVersion: 1
          datasources:
            - name: Prometheus
              type: prometheus
              url: http://prometheus-kube-prometheus-prometheus:9090
              access: proxy
              isDefault: true
            
            - name: Loki
              type: loki
              url: http://loki:3100
              access: proxy
      
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
            - name: default
              orgId: 1
              folder: ''
              type: file
              disableDeletion: false
              updateIntervalSeconds: 10
              allowUiUpdates: true
              options:
                path: /var/lib/grafana/dashboards/default

    alertmanager:
      enabled: true
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 1Gi

    nodeExporter:
      enabled: true

    kubeStateMetrics:
      enabled: true

---
# ===== 7. Nginx Ingress Controller =====
# Datei: clusters/dev/apps/ingress-nginx.yaml

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.9.1"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system

  values:
    controller:
      replicaCount: 2
      service:
        type: LoadBalancer
        loadBalancerIP: "192.168.100.201"
        annotations:
          cloud.google.com/neg: '{"ingress": true}'
      
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: monitoring
      
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
      
      resources:
        limits:
          cpu: 200m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi
      
      config:
        log-level: info
        enable-modsecurity: "true"
        enable-owasp-core-rules: "true"

---
# ===== 8. Cert-Manager =====
# Datei: clusters/dev/apps/cert-manager.yaml

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 30m
  chart:
    spec:
      chart: cert-manager
      version: "v1.12.0"
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system

  install:
    crds: Create
  update:
    crds: CreateReplace

  values:
    global:
      leaderElection:
        namespace: cert-manager
    
    installCRDs: true

---
# ClusterIssuers
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@cluster.local
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
      - http01:
          ingress:
            class: nginx

---
# ===== 9. Loki Logging Stack =====
# Datei: clusters/dev/apps/loki.yaml

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: logging
spec:
  interval: 30m
  chart:
    spec:
      chart: loki-stack
      version: "2.9.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system

  values:
    loki:
      persistence:
        enabled: true
        size: 10Gi
      
      config:
        auth_enabled: false
        
        limits_config:
          retention_deletes_enabled: true
          retention_period: 168h  # 7 days
          enforce_metric_name: false
          reject_old_samples: true
          reject_old_samples_max_age: 168h

    promtail:
      enabled: true
      
      config:
        clients:
          - url: http://loki:3100/loki/api/v1/push
        
        scrape_configs:
          - job_name: kubernetes-pods
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels: [__meta_kubernetes_pod_name]
                target_label: pod
              - source_labels: [__meta_kubernetes_namespace]
                target_label: namespace
              - source_labels: [__meta_kubernetes_pod_label_app]
                target_label: app

---
# ===== 10. External Secrets (für Secret Management) =====
# Datei: clusters/dev/infrastructure/external-secrets.yaml

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets-system
spec:
  interval: 30m
  chart:
    spec:
      chart: external-secrets
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system

  install:
    crds: Create
  update:
    crds: CreateReplace

---
# ===== 11. NetworkPolicy für Security =====
# Datei: clusters/dev/infrastructure/network-policies.yaml

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: default
spec:
  podSelector: {}
  policyTypes:
    - Ingress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-from-nginx
  namespace: default
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
        - podSelector:
            matchLabels:
              app: ingress-nginx

---
# ===== 12. RBAC für Teams =====
# Datei: clusters/dev/infrastructure/rbac.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: developer
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/logs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: developers-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: developer
subjects:
  - kind: Group
    name: "developers"
    apiGroup: rbac.authorization.k8s.io

---
# ===== 13. Pod Security Standards =====
# Datei: clusters/dev/infrastructure/pod-security.yaml

apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: restricted
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'MustRunAsNonRoot'
  seLinux:
    rule: 'MustRunAs'
    seLinuxOptions:
      level: "s0:c123,c456"
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  readOnlyRootFilesystem: false

---
# ===== 14. Example Application Deployment =====
# Datei: clusters/dev/apps/sample-app.yaml

apiVersion: v1
kind: Namespace
metadata:
  name: sample-app

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: sample-app
data:
  APP_ENV: "development"
  LOG_LEVEL: "debug"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: sample-app
  labels:
    app: sample-app
    version: v1
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  
  selector:
    matchLabels:
      app: sample-app
  
  template:
    metadata:
      labels:
        app: sample-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      
      containers:
        - name: app
          image: nginx:1.25
          imagePullPolicy: IfNotPresent
          
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_ENV
          
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      
      volumes:
        - name: tmp
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: sample-app
  namespace: sample-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: sample-app

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-app
  namespace: sample-app
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - sample-app.cluster.local
      secretName: sample-app-tls
  rules:
    - host: sample-app.cluster.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sample-app
                port:
                  number: 80

---
# ===== 15. Kustomization für Dev Apps =====
# Datei: clusters/dev/apps/kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - monitoring.yaml
  - ingress-nginx.yaml
  - cert-manager.yaml
  - loki.yaml
  - sample-app.yaml

# Gemeinsame Labels
commonLabels:
  environment: dev
  managed-by: flux

# Gemeinsame Annotations
commonAnnotations:
  flux.weave.works/sync-timestamp: "2024-01-01T00:00:00Z"

# Image updates (für Dependabot/Renovate)
images:
  - name: nginx
    newTag: "1.25"

# Replicas anpassen (dev: weniger replicas als prod)
replicas:
  - name: sample-app
    count: 1
  - name: prometheus
    count: 1

# Patchinge für Dev-Konfiguration
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: sample-app
    spec:
      replicas: 1
      template:
        spec:
          containers:
            - name: app
              resources:
                limits:
                  memory: 256Mi
